language: node_js
cache:
  directories:
  - node_modules
after_success: bash deploy
env:
  global:
    secure: K0smlXJApQKFSB+855OGf87SQQmgfxI2S8jI8F58qaxb0bmuW1yBFdmzA0qcsYRGOAf9JnHkSf9Iug81j1yizpqA5p6GmbWQZxoj465yd8EYHbL20Aw3qzED3YiDLAeK94HJtVaT/sXaqeM9aaezyUUiLTtRS5qe7tkYEFnPXEJZlqTU8VYrFlyqvr+2WilCi/ak2+MRQD2nQvw8XjegSAfHNyk+MjPjQuG9t2PD7S2Iz47zcKJc7ZHr4lptl4kgeJkG96+5mLVVKkqU7bhM9gUNLWyGvXGJQqa4fDO27/SZrXZrpqPJFKStMxEyhPWy+zCR7Qez3d6JlbG6w1Zecm2Qxye0g/6Icvd8sZd9tEa/PqTgcEhbL1jVnw76WmGLGi7rZdz6pk4JB+9VRcmHsv+YOPL5Z/iaV3NIHQ1vzF2YLTc4/UmcflL3Fo4OSaBdSUXWBEjQYAE3I0ABJH4/p0yLPcQMfV83W4EXdrPe5C1zbBBT3mue7bit+a3NFzQXy0G4fXMatl/cEEf8AH80udaW+tWCdtgfbT9XD9am/0ywV91c5VBsXEYe2OzNj9ZsI8PymE5fkgz6VOzqb8IlG3Sg1cVHFCqHfKu3Gu6yXln8u3psQK8CWx63s38bOc2zUxgX7DlGruSAyULiqYjNiUvjsDdC2Knhn3sBFnA+aUA=
